# Site settings
title: Arthur Lui
header-img: off #img/home-bg.jpg
header-color: "#353535"
email: luiarthur@gmail.com
description: "Bayesian Statistics / Computation / Research / Arthur Lui / Blog"
baseurl: ""
url: "http://luiarthur.github.io"
#twitter_username: SBootstrap
github_username:  luiarthur
facebook_username:  arthur.lui.90

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title #pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
safe: on

defaults:
  -
    scope:
      path: ""
    values:
      comments: "cucumber"
  -
    scope:
      path: ""
      type: "ucscNotes"
    values:
      layout: "notes"
      comments: "cucumber"
      dollar: "on"
  -
    scope:
      path: "ucsc_notes/bnp"
    values:
      ams: 241
  -
    scope:
      path: "ucsc_notes/am"
    values:
      ams: 211
  -
    scope:
      path: "ucsc_notes/ams5"
    values:
      ams: 5
  -
    scope:
      path: "ucsc_notes/bayesInf"
    values:
      ams: "206"
  -
    scope:
      path: "ucsc_notes/classicInf"
    values:
      ams: "205"
  -
    scope:
      path: "ucsc_notes/advBayesComputing"
    values:
      ams: 268
  -
    scope:
      path: "ucsc_notes/fye"
    values:
      ams: "fye"

##################
# http://jekyllrb.com/docs/collections/
collections:
  ucscNotes:
    output: true
    permalink: /ucsc_notes/:path/
