# Site settings
title: Arthur Lui
header-img: img/home-bg.jpg
header-color: "grey"
email: luiarthur@gmail.com
description: "Bayesian Statistics / Computation / Research / Arthur Lui / Blog"
baseurl: ""
url: "http://luiarthur.github.io"
#twitter_username: SBootstrap
github_username:  luiarthur
facebook_username:  arthur.lui.90

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]
  #extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments
permalink: /:title #pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

defaults:
  -
    scope:
      path: ""
    values:
      comments: fb
  -
    scope:
      path: ""
      type: "ucscNotes"
    values:
      layout: "notes"
      comments: "inlinedisqus"
      dollar: "on"
##################
# http://jekyllrb.com/docs/collections/
collections:
  ucscNotes:
    output: true
    permalink: /ucsc_notes/:path/
