# Site settings
title: Arthur Lui
header-img: off #img/home-bg.jpg
header-color: "#353535"
email: luiarthur@gmail.com
description: "Bayesian Statistics / Computation / Research / Arthur Lui / Blog"
baseurl: ""
url: "http://luiarthur.github.io"
#twitter_username: SBootstrap
github_username:  luiarthur
facebook_username:  arthur.lui.90

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title #pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
safe: on

defaults:
  -
    scope:
      path: ""
    values:
      comments: "disqus"
  -
    scope:
      path: ""
      type: "ucscNotes"
    values:
      layout: "notes"
      comments: "disqus"
      dollar: "on"
  -
    scope:
      path: "/ucsc_notes/bnp"
    values:
      ams: 241
  -
    scope:
      path: "/ucsc_notes/am"
    values:
      ams: 211
  -
    scope:
      path: "/ucsc_notes/ams5"
    values:
      ams: 5
  -
    scope:
      path: "ucsc_notes/bayesInf"
    values:
      ams: 206
  -
    scope:
      path: "ucsc_notes/classicInf"
    values:
      ams: 205
  -
    scope:
      path: "ucsc_notes/advBayesComputing"
    values:
      ams: 268
  -
    scope:
      path: "ucsc_notes/fye"
    values:
      ams: "fye"
  -
    scope:
      path: "ucsc_notes/lm"
    values:
      ams: 256
  -
    scope:
      path: "ucsc_notes/bayesModel"
    values:
      ams: 207
  -
    scope:
      path: "ucsc_notes/parallel"
    values:
      ams: 250
  -
    scope:
      path: "ucsc_notes/glm"
    values:
      ams: 274
  -
    scope:
      path: "ucsc_notes/survival"
    values:
      ams: 276

##################
# http://jekyllrb.com/docs/collections/
collections:
  ucscNotes:
    output: true
    permalink: /ucsc_notes/:path/

### Regularly:
# Remember to run `bundle install` before making any gem-related commits.
# - `bundle install`
# - `gem install update`
# - For updating / installation help, check:  https://jekyllrb.com/docs/installation/#ubuntu

# jekyll serve --incremental
# for drafts: jekyll serve --incremental --drafts
# OR 
# bundle exec jeykll serve --incremental
