#!/bin/bash

rm -f *.{pdf,png}

getucsc <<EOF
  cd advBayesComputing/hw/hw1/code/R/output
  get *
EOF

convert rmseblasso.pdf rmseblasso.png
convert rmsegdp.pdf rmsegdp.png
convert rmsessvn.pdf rmsessvn.png

convert lassoVssvnPP.pdf lassoVssvnPP.png
convert ssvnVlassoPP.pdf ssvnVlassoPP.png
convert lassoVssvnFF.pdf lassoVssvnFF.png
convert ssvnVlassoFF.pdf ssvnVlassoFF.png

convert Lblasso.pdf  Lblasso.png
convert Lgdp.pdf     Lgdp.png
convert Lssvn.pdf    Lssvn.png

convert L1blasso.pdf  L1blasso.png
convert L1gdp.pdf     L1gdp.png
convert L1ssvn.pdf    L1ssvn.png

rm -f *.pdf
