#!/bin/bash

rm -f *.{pdf,png}

getucsc <<EOF
  cd advBayesComputing/hw/hw1/code/R/output
  get *
EOF

convert rmseblasso.pdf rmseblasso.png
convert rmsegdp.pdf rmsegdp.png
convert rmsessvn.pdf rmsessvn.png

rm -f *.pdf
